# Configurations
title:            NN4Neurosim
longtitle:        Neural Networks for Neurosimulations
author:           Zhaoze Wang
email:            zhaozewang@yahoo.com
description: >
  Some neural network implementations for simulating neural systems.

version:          1.1.0
gitbook_version:  1.0.0

url:              'https://nn4neurosim.github.io'
baseurl:          ''
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     assets/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  collection_1:
    output: true
    permalink: /intro/:path/
    name: "Introduction"
  collection_2:
    output: true
    permalink: /rnn/:path/
    name: "Recurrent Neural Networks"
  # collection_3:
  #   output: true
  #   permalink: /mlp/:path/
  #   name: "Multi-Layer Perceptrons"
  collection_4:
    output: true
    permalink: /constraint/:path/
    name: "Constraints"
  collection_5:
    output: true
    permalink: /mask/:path/
    name: "Masks"
  collection_6:
    output: true
    permalink: /logs/:path/
    name: "Logs"

page_width: 900px

destination:      ./_site
incremental:      true
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
